import React, { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';

const LABELS={CLARIFICATION_REQUESTED:'Clarification Requested',FINDING_ACCEPTED:'Finding Accepted',OVERRIDE_PERFORMED:'Status Overridden',PREPROCESSED_DEMO_IMPORTED:'Sample Workspace Loaded',TENDER_CREATED:'Tender Created',TENDER_UPLOADED:'Tender Uploaded',REQUIREMENTS_EXTRACTED:'Requirements Extracted',CHECKLIST_APPROVED:'Checklist Approved',BIDDER_CREATED:'Bidder Added',BIDDER_FILES_UPLOADED:'Bidder Documents Uploaded',BIDDER_PROCESSED:'Bidder Processed',TENDER_EVALUATED:'Compliance Evaluated'};
const human=s=>(LABELS[s]||String(s||'Activity').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()));
const when=iso=>new Date(iso).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
function detailText(d={}){return [d.requirement&&`Requirement: ${d.requirement}`,d.bidder&&`Bidder: ${d.bidder}`,d.document&&`Evidence: ${d.document}`,d.original_file&&`Source: ${d.original_file}`,d.machine_status&&`Machine: ${d.machine_status}`,d.officer_status&&`Officer: ${d.officer_status}`,d.reason&&`Reason: ${d.reason}`].filter(Boolean).join(' · ')||'Recorded by BidLens';}
export default function AuditTrailScreen({tenderId=null}){
 const [logs,setLogs]=useState([]),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState('');
 useEffect(()=>{api.listTenders().then(async ts=>{const t=ts.find(x=>x.id===tenderId)||ts[0];if(!t)return[];return (await api.audit(t.id)).map(e=>({...e,tender:t.external_bid_id||String(t.id)}));}).then(setLogs).catch(e=>setError(e.message));},[tenderId]);
 const actions=useMemo(()=>[...new Set(logs.map(x=>x.action))],[logs]);
 const rows=useMemo(()=>logs.filter(x=>(filter==='all'||x.action===filter)&&(!q.trim()||`${x.actor} ${x.action} ${JSON.stringify(x.details)}`.toLowerCase().includes(q.toLowerCase()))),[logs,q,filter]);
 return <div className="mx-auto max-w-7xl space-y-6 p-8">
  <div className="border-b border-[#DED8D0] pb-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#8A8178]">Procurement record</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-[#27221F]">Audit Trail</h1><p className="mt-1 text-sm text-[#6F675F]">Chronological record of system and officer actions for the selected tender.</p></div><span className="text-sm font-medium text-[#6F675F]">{logs.length} recorded events</span></div></div>
  {error&&<div className="border-l-4 border-[#B3432E] bg-white px-4 py-3 text-sm text-[#6B2E22]">{error}</div>}
  <div className="flex flex-wrap gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search audit record" className="min-w-[240px] flex-1 rounded-md border border-[#D8D1C8] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#B3432E]"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-md border border-[#D8D1C8] bg-white px-3 py-2.5 text-sm"><option value="all">All actions</option>{actions.map(a=><option key={a} value={a}>{human(a)}</option>)}</select></div>
  <div className="overflow-hidden rounded-lg border border-[#D8D1C8] bg-white">{rows.length===0?<div className="p-10 text-center text-sm text-[#786F66]">No matching audit events.</div>:<div>{rows.map((e,i)=><div key={e.id} className="grid gap-3 border-b border-[#ECE7E1] px-5 py-4 last:border-0 md:grid-cols-[165px_12px_190px_1fr]"><div className="text-xs leading-5 text-[#746C64]">{when(e.timestamp)}<div className="font-medium text-[#3D3732]">{e.actor||'System'}</div></div><div className="relative hidden md:block"><span className="absolute left-1 top-1.5 h-2 w-2 rounded-full bg-[#B3432E]"/>{i<rows.length-1&&<span className="absolute left-[7px] top-4 h-[calc(100%+18px)] w-px bg-[#DDD6CE]"/>}</div><div><div className="text-sm font-semibold text-[#2B2523]">{human(e.action)}</div><div className="mt-1 font-mono text-[11px] text-[#8A8178]">{e.tender}</div></div><div className="text-sm leading-6 text-[#5F5750]">{detailText(e.details)}</div></div>)}</div>}</div>
  <p className="text-xs text-[#8A8178]">Events are displayed in recorded order with actor, action, tender reference and available decision context.</p>
 </div>;
}