import { useEffect, useState } from "react";
import { api } from "@/lib/api";

export default function BidderWorkspace({ tender, onOpenCompliance }) {
  const [bidders,setBidders]=useState([]); const [form,setForm]=useState({bidder_id:"",bidder_name:""}); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const refresh=()=>api.listBidders(tender.id).then(setBidders);
  useEffect(()=>{refresh().catch(e=>setError(e.message));},[tender.id]);
  const run=async(label,fn)=>{setBusy(label);setError("");try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy("");}};
  return <div className="mx-auto max-w-7xl space-y-5 p-7"><div className="flex items-start justify-between"><div><p className="text-sm text-[#786F66]">{tender.external_bid_id}</p><h1 className="text-2xl font-extrabold">Bidder Workspace</h1><p className="text-sm text-[#786F66]">Add bidder records, upload their real PDF packs, and run the existing classification/evidence pipeline.</p></div><button onClick={onOpenCompliance} className="rounded-lg bg-[#2B2523] px-4 py-2 font-bold text-white">Compliance & Registries</button></div>
    {error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <form onSubmit={e=>{e.preventDefault();run("create",async()=>{await api.createBidder(tender.id,form);setForm({bidder_id:"",bidder_name:""});});}} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-[1fr_2fr_auto]"><input aria-label="Bidder ID" required placeholder="Bidder ID" value={form.bidder_id} onChange={e=>setForm({...form,bidder_id:e.target.value})} className="rounded-lg border p-3"/><input aria-label="Bidder name" required placeholder="Registered bidder name" value={form.bidder_name} onChange={e=>setForm({...form,bidder_name:e.target.value})} className="rounded-lg border p-3"/><button disabled={!!busy} className="rounded-lg bg-[#B3432E] px-5 font-bold text-white">Add Bidder</button></form>
    <div className="space-y-4">{bidders.length===0&&<div className="rounded-2xl border bg-white p-10 text-center text-[#786F66]">No bidders yet. Add the first bidder above.</div>}{bidders.map(b=><BidderCard key={b.id} bidder={b} busy={busy} run={run}/>)}</div>
  </div>;
}

function BidderCard({bidder,busy,run}) {
  const upload=async(event)=>{const files=event.target.files;if(files?.length)await run(`upload-${bidder.id}`,()=>api.uploadBidderFiles(bidder.id,files));event.target.value="";};
  return <div className="rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-extrabold">{bidder.bidder_name}</h2><p className="text-sm text-[#786F66]">{bidder.bidder_id} · {bidder.overall_status}</p></div><div className="flex gap-2"><label className="cursor-pointer rounded-lg border px-4 py-2 text-sm font-bold">{busy===`upload-${bidder.id}`?"Uploading…":"Upload PDFs"}<input aria-label={`Upload PDFs for ${bidder.bidder_name}`} type="file" accept="application/pdf" multiple className="hidden" onChange={upload}/></label><button onClick={()=>run(`process-${bidder.id}`,()=>api.processBidder(bidder.id))} disabled={!bidder.uploaded_files?.length||!!busy} className="rounded-lg bg-[#B3432E] px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{busy===`process-${bidder.id}`?"Classifying & extracting…":"Process with AI"}</button></div></div>
    <div className="grid gap-5 p-5 lg:grid-cols-2"><section><h3 className="mb-2 text-sm font-extrabold">Uploaded source PDFs ({bidder.uploaded_files?.length||0})</h3><div className="max-h-64 space-y-1 overflow-auto">{(bidder.uploaded_files||[]).map(f=><button key={f.filename} onClick={()=>window.open(api.absoluteUrl(`${f.url}#page=1`),"_blank")} className="block w-full rounded bg-[#FAF8F5] px-3 py-2 text-left text-xs hover:bg-[#F0EBE4]">{f.filename} · merged pages {f.page_start}-{f.page_end}</button>)}</div></section><section><h3 className="mb-2 text-sm font-extrabold">Classified documents ({bidder.documents?.length||0})</h3><div className="max-h-64 space-y-1 overflow-auto">{(bidder.documents||[]).map(d=><div key={d.document_id} className="rounded bg-[#FAF8F5] px-3 py-2 text-xs"><b>{d.category}</b> · {d.document_title||d.document_id} · page {d.page_start} · confidence {d.confidence??"—"}</div>)}</div></section></div></div>;
}
