import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { PdfModal } from "@/components/PdfViewer";

const EMPTY = { name:"", category:"", description:"", operator:"EXISTS", required_value:"", unit:"", mandatory:true, required_document_type:"", source_page:"", source_text:"", applicable:true };

function RequirementForm({ initial = EMPTY, onSave, onCancel }) {
  const [value, setValue] = useState({...EMPTY, ...initial, source_page:initial.source_page ?? initial.source?.page ?? "", source_text:initial.source_text ?? initial.source?.text ?? ""});
  const submit = (event) => { event.preventDefault(); const payload = {name:value.name, category:value.category, description:value.description, operator:value.operator, required_value:value.required_value === "" || value.required_value == null ? null : Number(value.required_value), unit:value.unit || null, mandatory:value.mandatory, required_document_type:value.required_document_type || null, source_page:value.source_page === "" ? null : Number(value.source_page), source_text:value.source_text || null, applicable:value.applicable}; onSave(payload); };
  return <form onSubmit={submit} className="grid gap-3 rounded-xl border bg-[#FAF8F5] p-4 md:grid-cols-2">
    <label className="text-xs font-bold">Name<input aria-label="Requirement name" required className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label>
    <label className="text-xs font-bold">Category<input aria-label="Requirement category" required className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.category} onChange={e=>setValue({...value,category:e.target.value})}/></label>
    <label className="text-xs font-bold md:col-span-2">Description<textarea aria-label="Requirement description" required className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label>
    <label className="text-xs font-bold">Operator<select aria-label="Requirement operator" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.operator} onChange={e=>setValue({...value,operator:e.target.value})}>{["EXISTS","EXACT_IDENTIFIER_MATCH","GREATER_THAN_OR_EQUAL","LOCAL_CONTENT_CLASSIFICATION","BIDDER_NAME_MATCH","MANUAL_REVIEW"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label className="text-xs font-bold">Document type<input aria-label="Required document type" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.required_document_type || ""} onChange={e=>setValue({...value,required_document_type:e.target.value})}/></label>
    <label className="text-xs font-bold">Required value<input aria-label="Required value" type="number" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.required_value ?? ""} onChange={e=>setValue({...value,required_value:e.target.value})}/></label>
    <label className="text-xs font-bold">Source page<input aria-label="Source page" type="number" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.source_page ?? value.source?.page ?? ""} onChange={e=>setValue({...value,source_page:e.target.value})}/></label>
    <label className="text-xs font-bold md:col-span-2">Tender source text<textarea aria-label="Tender source text" className="mt-1 w-full rounded-lg border bg-white p-2 text-sm font-normal" value={value.source_text ?? value.source?.text ?? ""} onChange={e=>setValue({...value,source_text:e.target.value})}/></label>
    <div className="flex gap-2 md:col-span-2"><button className="rounded-lg bg-[#B3432E] px-4 py-2 text-sm font-bold text-white">Save Requirement</button><button type="button" onClick={onCancel} className="rounded-lg border bg-white px-4 py-2 text-sm">Cancel</button></div>
  </form>;
}

export default function TenderWorkspace({ tender, onRefresh, onOpenBidders }) {
  const [requirements, setRequirements] = useState([]); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [editing,setEditing]=useState(null); const [adding,setAdding]=useState(false); const [detail,setDetail]=useState(tender); const [sourcePage,setSourcePage]=useState(null);
  const refresh = async () => { const [reqs, latest] = await Promise.all([api.requirements(tender.id), api.tender(tender.id)]); setRequirements(reqs); setDetail(latest); onRefresh?.(); };
  useEffect(()=>{ refresh().catch(e=>setError(e.message)); },[tender.id]);
  const action = async (label, fn) => { setBusy(label); setError(""); try { await fn(); await refresh(); } catch(e){setError(e.message);} finally{setBusy("");} };
  const applicableManual = requirements.filter(r=>r.applicable && r.operator==="MANUAL_REVIEW").length;
  return <div className="mx-auto max-w-7xl space-y-5 p-7">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-[#786F66]">Tender Workspace</p><h1 className="text-2xl font-extrabold">{detail.external_bid_id}</h1><p className="mt-1 font-semibold">{detail.title}</p><p className="text-sm text-[#786F66]">{detail.department} · {detail.status}</p></div><div className="flex gap-2">{detail.document_url&&<button type="button" onClick={()=>setSourcePage(1)} className="rounded-lg border bg-white px-4 py-2 text-sm font-bold">View Tender PDF</button>}<button onClick={onOpenBidders} className="rounded-lg bg-[#2B2523] px-4 py-2 text-sm font-bold text-white">Bidder Workspace</button></div></div>
    {error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-extrabold">AI Requirement Extraction</h2><p className="text-sm text-[#786F66]">Runs the existing qwen2.5:3b and all-MiniLM-L6-v2 pipeline.</p></div><button onClick={()=>action("extract",()=>api.extractTender(tender.id))} disabled={!!busy} className="rounded-lg bg-[#B3432E] px-5 py-2.5 font-bold text-white disabled:opacity-50">{busy==="extract"?"Extracting with AI…":"Extract Requirements"}</button></div></div>
    <div className="rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-extrabold">Requirement Review</h2><p className="text-sm text-[#786F66]">{requirements.length} normalized · {requirements.filter(r=>!r.applicable).length} not applicable · {applicableManual} applicable manual review</p></div><div className="flex gap-2"><button onClick={()=>setAdding(true)} className="rounded-lg border px-4 py-2 text-sm font-bold">Add Requirement</button><button onClick={()=>action("approve",()=>api.approveRequirements(tender.id))} disabled={!requirements.length||!!busy||applicableManual>0} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">{busy==="approve"?"Approving…":"Approve Checklist"}</button></div></div>
      <div className="space-y-3 p-5">{adding&&<RequirementForm onCancel={()=>setAdding(false)} onSave={payload=>action("add",async()=>{await api.addRequirement(tender.id,payload);setAdding(false);})}/>} {requirements.length===0&&<p className="py-8 text-center text-sm text-[#786F66]">Upload complete. Run extraction to generate requirements from the tender.</p>}
      {requirements.map(r=><div key={r.id} className="rounded-xl border p-4">{editing===r.id?<RequirementForm initial={r} onCancel={()=>setEditing(null)} onSave={payload=>action("edit",async()=>{await api.patchRequirement(r.id,payload);setEditing(null);})}/>:<div className="flex gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-extrabold">{r.requirement_id} · {r.name}</span><span className={`rounded-full px-2 py-0.5 text-xs ${r.applicable?"bg-emerald-50 text-emerald-700":"bg-gray-100 text-gray-600"}`}>{r.applicable?"APPLICABLE":"NOT_APPLICABLE"}</span><span className="rounded-full bg-sky-50 px-2 py-0.5 text-xs text-sky-700">{r.operator}</span></div><p className="mt-2 text-sm text-[#574E46]">{r.description}</p><div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-[#786F66]"><span>{r.category} · {r.required_document_type||"No document type"}</span>{r.source?.page&&detail.document_url&&<button type="button" onClick={()=>setSourcePage(r.source.page)} className="font-bold text-[#B3432E] underline-offset-2 hover:underline">View Tender Source · Page {r.source.page}</button>}</div><details className="mt-2 text-xs"><summary className="cursor-pointer font-bold">Tender source text</summary><p className="mt-1 rounded bg-[#FAF8F5] p-2">{r.source?.text||"No source text because this category was not found."}</p></details></div><div className="flex shrink-0 gap-2"><button onClick={()=>setEditing(r.id)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Edit</button><button onClick={()=>{if(window.confirm(`Delete ${r.requirement_id}?`)) action("delete",()=>api.deleteRequirement(r.id));}} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-bold text-red-700">Delete</button></div></div>}</div>)}</div>
    </div>
    {sourcePage&&<PdfModal url={api.absoluteUrl(detail.document_url)} page={sourcePage} title={`${detail.external_bid_id} tender source`} onClose={()=>setSourcePage(null)}/>}
  </div>;
}
